apiVersion: v1
kind: Pod
metadata:
 name: minecraft-pod
 labels:
  app: minecraft-server
spec:
 containers:
 - name: minecraft-service
   image: openhack/minecraft-server:2.0
   ports:
   - containerPort: 25565
     name: service
   - containerPort: 25575
     name: admin
   env:
   - name: "EULA"
     value: "TRUE"