apiVersion: v1
kind: Service
metadata:
 name: minecraft-server-service
spec:
 type: LoadBalancer
 ports:
 - port: 25565
   name: service
 - port: 25575
   name: admin
 selector:
   app: minecraft-server